Given(/^I wait for "([^"]*)" s$/)
Given(/^I upload a product image$/)
When(/^I click on "([^"]*)" "([^"]*)"$/)
When(/^I press on "([^"]*)" "([^"]*)"$/)
When(/^I check on "([^"]*)" "([^"]*)"$/)
When(/^I change window size to "([^"]*)" x "([^"]*)"$/)
Given(/^(?:|I )am on (?:|the )homepage$/)
When(/^(?:|I )go to (?:|the )homepage$/)
Given(/^(?:|I )am on "([^"]*)"$/)
When(/^(?:|I )go to "([^"]*)"$/)
When(/^(?:|I )reload the page$/)
When(/^(?:|I )move backward one page$/)
When(/^(?:|I )move forward one page$/)
When(/^(?:|I )press "([^"]*)"$/)
When(/^(?:|I )follow "([^"]*)"$/)
When(/^(?:|I )fill in "([^"]*)" with "([^"]*)"$/)
When(/^(?:|I )fill in "([^"]*)" with:$/)
When(/^(?:|I )fill in "([^"]*)" for "([^"]*)"$/)
When(/^(?:|I )fill in the following:$/)
When(/^(?:|I )select "([^"]*)" from "([^"]*)"$/)
When(/^(?:|I )additionally select "([^"]*)" from "([^"]*)"$/)
When(/^(?:|I )check "([^"]*)"$/)
When(/^(?:|I )uncheck "([^"]*)"$/)
When(/^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/)
Then(/^(?:|I )should be on "([^"]*)"$/)
Then(/^(?:|I )should be on (?:|the )homepage$/)
Then(/^the (?i)url(?-i) should match (?P<pattern>"(?:[^"]|\\")*")$/)
Then(/^the response status code should be 0$/)
Then(/^the response status code should not be 0$/)
Then(/^(?:|I )should see "([^"]*)"$/)
Then(/^(?:|I )should not see "([^"]*)"$/)
Then(/^(?:|I )should see text matching (?P<pattern>"(?:[^"]|\\")*")$/)
Then(/^(?:|I )should not see text matching (?P<pattern>"(?:[^"]|\\")*")$/)
Then(/^the response should contain "([^"]*)"$/)
Then(/^the response should not contain "([^"]*)"$/)
Then(/^(?:|I )should see "([^"]*)" in the "([^"]*)" element$/)
Then(/^(?:|I )should not see "([^"]*)" in the "([^"]*)" element$/)
Then(/^the "([^"]*)" element should contain "([^"]*)"$/)
Then(/^the "([^"]*)" element should not contain "([^"]*)"$/)
Then(/^(?:|I )should see an? "([^"]*)" element$/)
Then(/^(?:|I )should not see an? "([^"]*)" element$/)
Then(/^the "([^"]*)" field should contain "([^"]*)"$/)
Then(/^the "([^"]*)" field should not contain "([^"]*)"$/)
Then(/^(?:|I )should see 0 "([^"]*)" elements?$/)
Then(/^the "([^"]*)" checkbox should be checked$/)
Then(/^the "([^"]*)" checkbox is checked$/)
Then(/^the checkbox "([^"]*)" (?:is|should be) checked$/)
Then(/^the "([^"]*)" checkbox should (?:be unchecked|not be checked)$/)
Then(/^the "([^"]*)" checkbox is (?:unchecked|not checked)$/)
Then(/^the checkbox "([^"]*)" should (?:be unchecked|not be checked)$/)
Then(/^the checkbox "([^"]*)" is (?:unchecked|not checked)$/)
Then(/^print current URL$/)
Then(/^print last response$/)
Then(/^show last response$/)

